# TCL File Generated by Component Editor 12.1sp1
# Fri Apr 08 07:48:05 MDT 2016
# DO NOT MODIFY


# 
# sdramBuffer "sdramBuffer" v1.0
# null 2016.04.08.07:48:05
# 
# 

# 
# request TCL package from ACDS 12.1
# 
package require -exact qsys 12.1


# 
# module sdramBuffer
# 
set_module_property NAME sdramBuffer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME sdramBuffer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL sdramBuffer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file sdramBuffer.vhd VHDL PATH sdramBuffer.vhd


# 
# parameters
# 
add_parameter AUTO_CLOCK_CLOCK_RATE STRING -1
set_parameter_property AUTO_CLOCK_CLOCK_RATE DEFAULT_VALUE -1
set_parameter_property AUTO_CLOCK_CLOCK_RATE DISPLAY_NAME AUTO_CLOCK_CLOCK_RATE
set_parameter_property AUTO_CLOCK_CLOCK_RATE TYPE STRING
set_parameter_property AUTO_CLOCK_CLOCK_RATE UNITS None
set_parameter_property AUTO_CLOCK_CLOCK_RATE HDL_PARAMETER true
add_parameter base_addr STD_LOGIC_VECTOR 0
set_parameter_property base_addr DEFAULT_VALUE 0
set_parameter_property base_addr DISPLAY_NAME base_addr
set_parameter_property base_addr TYPE STD_LOGIC_VECTOR
set_parameter_property base_addr UNITS None
set_parameter_property base_addr ALLOWED_RANGES 0:4294967295
set_parameter_property base_addr HDL_PARAMETER true
add_parameter buffersize STD_LOGIC_VECTOR 10568
set_parameter_property buffersize DEFAULT_VALUE 10568
set_parameter_property buffersize DISPLAY_NAME buffersize
set_parameter_property buffersize TYPE STD_LOGIC_VECTOR
set_parameter_property buffersize UNITS None
set_parameter_property buffersize ALLOWED_RANGES 0:4294967295
set_parameter_property buffersize HDL_PARAMETER true


# 
# display items
# 


# 
# connection point m0
# 
add_interface m0 avalon start
set_interface_property m0 addressUnits SYMBOLS
set_interface_property m0 associatedClock clock
set_interface_property m0 associatedReset reset
set_interface_property m0 bitsPerSymbol 8
set_interface_property m0 burstOnBurstBoundariesOnly false
set_interface_property m0 burstcountUnits WORDS
set_interface_property m0 doStreamReads false
set_interface_property m0 doStreamWrites false
set_interface_property m0 holdTime 0
set_interface_property m0 linewrapBursts false
set_interface_property m0 maximumPendingReadTransactions 0
set_interface_property m0 readLatency 0
set_interface_property m0 readWaitTime 1
set_interface_property m0 setupTime 0
set_interface_property m0 timingUnits Cycles
set_interface_property m0 writeWaitTime 0
set_interface_property m0 ENABLED true

add_interface_port m0 avm_m0_address address Output 32
add_interface_port m0 avm_m0_read read Output 1
add_interface_port m0 avm_m0_waitrequest waitrequest Input 1
add_interface_port m0 avm_m0_readdata readdata Input 16
add_interface_port m0 avm_m0_write write Output 1
add_interface_port m0 avm_m0_writedata writedata Output 16
add_interface_port m0 avm_m0_readdatavalid readdatavalid Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset reset reset_n Input 1


# 
# connection point streaming_in
# 
add_interface streaming_in avalon_streaming end
set_interface_property streaming_in associatedClock clock
set_interface_property streaming_in associatedReset reset
set_interface_property streaming_in dataBitsPerSymbol 8
set_interface_property streaming_in errorDescriptor ""
set_interface_property streaming_in firstSymbolInHighOrderBits true
set_interface_property streaming_in maxChannel 0
set_interface_property streaming_in readyLatency 0
set_interface_property streaming_in ENABLED true

add_interface_port streaming_in buffer_in_valid valid Input 1
add_interface_port streaming_in buffer_in data Input 16


# 
# connection point streaming_out
# 
add_interface streaming_out avalon_streaming start
set_interface_property streaming_out associatedClock clock
set_interface_property streaming_out associatedReset reset
set_interface_property streaming_out dataBitsPerSymbol 8
set_interface_property streaming_out errorDescriptor ""
set_interface_property streaming_out firstSymbolInHighOrderBits true
set_interface_property streaming_out maxChannel 0
set_interface_property streaming_out readyLatency 0
set_interface_property streaming_out ENABLED true

add_interface_port streaming_out buffer_out_valid valid Output 1
add_interface_port streaming_out buffer_out data Output 16

